name: Publish to Launchpad PPA

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dput devscripts debhelper dh-python python3-all python3-setuptools build-essential lintian

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(grep "^linchat" pkg/debian/changelog | head -n 1 | sed -E 's/^linchat \(([0-9]+\.[0-9]+\.[0-9]+)-.+\).+$/\1/')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is $VERSION"

      - name: Setup GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.LAUNCHPAD_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.LAUNCHPAD_GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$GPG_PASSPHRASE" | gpg --batch --passphrase-fd 0 --pinentry-mode loopback -ab README.md

      - name: Identify Ubuntu versions
        id: ubuntu_versions
        run: |
          UBUNTU_VERSIONS=("focal" "jammy" "noble")
          echo "UBUNTU_VERSIONS=${UBUNTU_VERSIONS[*]}" >> $GITHUB_ENV

      - name: Prepare and build for each Ubuntu version
        run: |
          mkdir -p ~/ppa-builds
          cp -r pkg/debian ./debian

          # Ensure changelog has proper format and version
          for UBUNTU_VERSION in $UBUNTU_VERSIONS; do
            PACKAGE_VERSION="${VERSION}-1~${UBUNTU_VERSION}1"
            cp -r . ~/ppa-builds/linchat-$UBUNTU_VERSION
            cd ~/ppa-builds/linchat-$UBUNTU_VERSION
            
            # Create updated changelog entry
            dch --create --package linchat --newversion $PACKAGE_VERSION --distribution $UBUNTU_VERSION "Release for $UBUNTU_VERSION"
            
            # Build source package
            debuild -S -sa -k${{ secrets.LAUNCHPAD_GPG_KEY_ID }}
            
            cd -
          done

      - name: Upload to Launchpad PPA
        run: |
          # Configure dput
          echo "[launchpad-ppa]" > ~/.dput.cf
          echo "fqdn = ppa.launchpad.net" >> ~/.dput.cf
          echo "method = ftp" >> ~/.dput.cf
          echo "incoming = ~${{ secrets.LAUNCHPAD_USERNAME }}/ubuntu/linchat/" >> ~/.dput.cf
          echo "login = anonymous" >> ~/.dput.cf
          echo "allow_unsigned_uploads = 0" >> ~/.dput.cf
          
          # Upload each source package
          for UBUNTU_VERSION in $UBUNTU_VERSIONS; do
            PACKAGE_VERSION="${VERSION}-1~${UBUNTU_VERSION}1"
            dput launchpad-ppa ~/ppa-builds/linchat_${PACKAGE_VERSION}_source.changes
          done